language: python
addons:
  apt:
    update: true
sudo: false
cache: pip
git:
  depth: false

python:
  - 2.7

script:
  - make check

install:
  - sudo apt install python-all-dev subunit python-debian python-apt python-testtools patchutils pristine-tar devscripts
  - travis_retry pip install -U setuptools
  - travis_retry pip install -U pip coverage codecov flake8 testtools paramiko cython six docutils python-subunit bzr+lp:brz mercurial

after_success:
  - codecov
